config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'

  resources :users 
  resources :posts
  

  get 'static_pages/show/:id', to: 'static_pages#show', as: :show

  get '/archive/:id', to: 'posts#archived', as: :archive

  get 'static_pages/about'

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_attached_file :image, :styles => {icon: "32x32!", :medium => "300x300!>", :thumb => "100x100!>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @post = Post.find(params[:id])
    @posts = Post.paginate(:page => params[:page], :per_page => 3)
    @thePosts = Post.all
    @archived_posts = @thePosts.where(archive: true)
    @unarchived_posts = @posts.where(archive: false)

    # adminMaker = User.find_by(email: "jobenscott@yahoo.com")
    # adminMaker.add_role :admin

    @aaron = User.find_by(email: "jobenscott@yahoo.com")
    @ray = User.find_by(email: "rayeveleth@gmail.com")

  end

  def created_today?
    @archived_posts.created_at.to_date == Date.today
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def archived
    @post = Post.find(params[:id])

    @post.update_attributes(archive: true)
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

    def post_params
      params.require(:post).permit(:subject, :content, :image, :archive)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # @post = Post.find(params[:id])
    @posts = Post.paginate(:page => params[:page], :per_page => 3)
    @thePosts = Post.all
    @archived_posts = @thePosts.where(archive: true)
    @unarchived_posts = @posts.where(archive: false)
    # @user = User.find(params[:id])

    # adminUser = User.find_by(email: "rayeveleth@gmail.com")
    # adminUser.add_role :admin

    # adminMaker = User.find_by(email: "jobenscott@yahoo.com")
    # adminMaker.add_role :admin

    @aaron = User.find_by(email: "jobenscott@yahoo.com")
    @ray = User.find_by(email: "rayeveleth@gmail.com")


  end

  

  def about

    @aaron = User.find_by(email: "jobenscott@yahoo.com")
    @ray = User.find_by(email: "rayeveleth@gmail.com")
  end

  def show
    @post = Post.find(params[:id])
  end


  private
  
    def user_params
        params.require(:user).permit(:email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @aaron = User.find_by(email: "jobenscott@yahoo.com")
    @ray = User.find_by(email: "rayeveleth@gmail.com")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dadsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

</body>
</html>

app/views/posts/_index.html.erb
<h4 class="postTitle">Recent Posts</h4>

<% if current_user == @aaron || current_user == @ray %>
<div class="newPostButton">
      <%= link_to "", new_post_path(current_user), class: "graybtn fa fa-pencil-square-o fa-lg"%>
</div>
<% end %>
<% @unarchived_posts.each do |post| %>
<div class="indexPostImage">           
      <div class="imageIndex"><%= image_tag post.image.url(:thumb) %></div>
</div>

<div class="movingBoxIndex">

<!-- <button href="#" id="summaryShow" class="optionButtons">test</button> -->
      <br>
      <span class="postTime">Post was made <%= time_ago_in_words(post.created_at) %> ago</span>

      <%= link_to 'Show', show_path(post), class: "optionButtons" %> 
      <!-- <button class="optionButtons">Show Summary</button> -->
      <div class="optionButtons summaryShow">Subject</div>
      <%#= if can? :update, post %>
      <% if current_user == @ray || current_user == @aaron %>
      <div class="optionsButton optionButtons">Options</div>
      <div class="backFromOptions optionButtons">>></div>

      <%= link_to 'Edit', edit_post_path(post.id), class: "optionsHidden optionButtons" %> 
      <%= link_to 'Delete', post_path(post), method: :delete, class: "optionsHidden optionButtons" %>
      <%= link_to "Archive", archive_path(post), class: "optionsHidden optionButtons"%>
      <% end %>
      <!-- <div class="hiddenButtonTwo"></div> -->

</div>
<div class="showContentOnSlide"><%= post.subject %></div>
<div class="indexPostBack optionButtons">Back</div>
<hr class="shortHoverRow">
<div class="hiddenButton"></div>
<!-- <div class="hiddenButtonThree"></div> -->
<br>
<br>
<% end %>

<div class="postPagination"><%= will_paginate @posts %></div>

        

app/views/posts/_post_form.html.erb
<%= bootstrap_form_for @post, :url => posts_path, :html => { :multipart => true } do |f| %>
  
    <%= f.text_field :subject %>

    <%= f.text_area :content %>

    <%= f.file_field :image, label: "Add Image"%>

    <%= f.submit class: "btn btn-info" %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render 'post_form' %>

app/views/posts/new.html.erb
<%= render 'post_form' %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/static_pages/_footer.html.erb
<div class="footerHome navbar navbar-fixed-bottom"><div>

app/views/static_pages/about.html.erb
<div id="thickNav">
  <%= link_to "Home", root_path, class: "homeButton" %>
  <%= link_to "About", static_pages_about_path, class: "aboutButton" %>

</div>


<div class="container">
<h2 class="aboutTitle">About the Cause</h2>
<p class="aboutContent">
  Well howdy everyone! This is my blog, about Iron Men, and other questionable fantasies. I enjoy getting no sleep and waking up at incredibly unreasonable hours. If you can't tell I don't have much to write so I'm making it up as I go. If I was a boy, something cause I'm Riahnna, and I really do not know how to spell that name! Woooh! 
</p>
</div>

<% #if current_user == @aaron || current_user == @ray %>
<%#= current_user.email %>
<% #end %>
<%= link_to "Sign Up", new_user_path %>
<%= link_to "Sign In", new_user_session_path %>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

app/views/static_pages/home.html.erb
<div class="image">
  <!-- <img class="longPic" src="http://imgprix.com/web/wallpapers/colorful-sky-ocean/1920x1080.jpg"> -->
  </div>

  <!-- <div class="carousel">

  </div>
  <div id="rightCarousel" class="carousel">

  </div> -->
  <div id="thickNav">
  <%= link_to "Home", root_path, class: "homeButton" %>
  <%= link_to "About", static_pages_about_path, class: "aboutButton" %>

</div>

<%# if current_user == @aaron || current_user == @ray %>
<%#= current_user.email %>

<%#= link_to "Sign Up", new_user_path %>
<%#= link_to "Sign In", new_user_session_path %>
<%#= link_to "Sign Out", destroy_user_session_path, :method => :delete %>





<div class="row">        


  <div class="col-md-9 postContent">
    <%= render 'posts/index' %>  
  </div>

  
  <div class="col-md-3 rightArchived">
    <h4 class="archivedTitle">Archived Posts</h4>
        <div class="archivedHeadingOne">Today</div>
        <div class="archivedTimeDisplayedOne">  
          <% @archived_posts.each do |apost| %> 
            <% if apost.created_at == Date.today && apost.content.length > 45 %>
              <div>too long</div>
            <% elsif apost.created_at == Date.today %>
              <p>Post was made <%= time_ago_in_words(apost.created_at) %> ago</p>
              <div class="archivedImageOne"><%= link_to image_tag(apost.image.url(:thumb)), show_path(apost) %></div>
              <div class="archivedHiddenSubject"><%= apost.subject %></div>
            <% end %>
          <% end %>
        </div>
       
        <div class="archivedHeadingTwo">Yesterday</div>
        <div class="archivedTimeDisplayedTwo">
          <% @archived_posts.each do |apost| %>
            <% if apost.created_at == 1.day.ago && apost.content.length > 45 %>
              <div>too long</div>
            <% elsif apost.created_at == 1.day.ago %>
              <p>Post was made <%= time_ago_in_words(apost.created_at) %> ago</p>
              <div class="archivedImageTwo"><%= link_to image_tag(apost.image.url(:thumb)), show_path(apost) %></div>
              <div class="archivedHiddenSubject"><%= apost.subject %></div>
            <% end %>
          <% end %>
        </div>
        
        <div class="archivedHeadingThree">1 Week Ago</div>
        <div class="archivedTimeDisplayedThree">
          <% @archived_posts.each do |apost| %>
            <% if apost.created_at >= 1.week.ago && apost.created_at < 1.day.ago && apost.content.length > 45 %>
              <div>too long</div>
            <% elsif apost.created_at >= 1.week.ago && apost.created_at < 1.day.ago %>
              <p>Post was made <%= time_ago_in_words(apost.created_at) %> ago</p>
              <div class="archivedImageThree"><%= link_to image_tag(apost.image.url(:thumb)), show_path(apost) %></div>
              <div class="archivedHiddenSubject"><%= apost.subject %></div>
            <% end %>
          <% end %>
        </div>
        
        <div class="archivedHeadingFour">2 Weeks Ago</div>
        
          <% @archived_posts.each do |apost| %>
          
            <% if apost.created_at >= 2.week.ago && apost.created_at < 1.week.ago && apost.content.length > 45 %>
              <div>too long</div>
            <% elsif apost.created_at >= 2.week.ago && apost.created_at < 1.week.ago %>
            <div class="archivedTimeDisplayedFour panel panel-md">
              <p class="archivedTimeCounter">Post was made <%= time_ago_in_words(apost.created_at) %> ago</p>
              <div class="archivedImageFour"><%= image_tag apost.image.url(:thumb) %></div>
              <div class="archivedHiddenSubject"><%= link_to apost.subject, show_path(apost), class: "archivedSubjectColor" %></div>
              </div>
            <% end %>           
          <% end %>
        
                
        <div class="archivedHeadingFive">3 Weeks Ago</div>
        <div class="archivedTimeDisplayedFive">
          <% @archived_posts.each do |apost| %>
            <% if apost.created_at >= 3.week.ago && apost.created_at < 2.week.ago && apost.content.length > 45 %>
              <div>too long</div>
            <% elsif apost.created_at >= 3.week.ago && apost.created_at < 2.week.ago %>
              <p>Post was made <%= time_ago_in_words(apost.created_at) %> ago</p>
              <div class="archivedImageFive"><%= link_to image_tag(apost.image.url(:thumb)), show_path(apost) %></div>
                <div class="archivedHiddenSubject"><%= apost.subject %></div>
            <% end %>
          <% end %>
          </div>
        
               
        <div class="archivedHeadingSix">1 Month Ago</div>
        <div class="archivedTimeDisplayedSix">
          <% @archived_posts.each do |apost| %>
            <% if apost.created_at >= 1.month.ago && apost.created_at < 3.week.ago && apost.content.length > 45 %> 
            <% elsif apost.created_at >= 1.month.ago && apost.created_at < 3.week.ago %>
              <p>Post was made <%= time_ago_in_words(apost.created_at) %> ago</p>
              <div class="archivedImageSix"><%= link_to image_tag(apost.image.url(:thumb)), show_path(apost) %></div>
              <div class="archivedHiddenSubject"><%= apost.subject %></div>
            <% end %>
          <% end %>
        </div>

  </div>


</div>

<%= render 'footer' %>

     

app/views/static_pages/show.html.erb
<div id="thickNav">
  <%= link_to "Home", root_path, class: "homeButton" %>
  <%= link_to "About", static_pages_about_path, class: "aboutButton" %>
</div>

  <div class="showPlat">
  <div class="showContent"><%= @post.content %></div>
  </div>
  <div class="imageShow"><%= image_tag @post.image.url %></div>
  <%= link_to 'Edit', edit_post_path(@post) %> | 
  <%= link_to 'Delete', post_path(@post), method: :delete %>

<%= render 'footer' %>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>

<% if current_user == @aaron || current_user == @ray %>
<%= current_user.email %>
<% end %>


<%= link_to "Sign Up", new_user_registration_path %>
<%= link_to "Sign In", new_user_session_path %>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>